### ISSUE TITLE
Call to a member function getBody() on null when trying to connect

### ISSUE THREAD

**Issue by ksonia90** [dcblogdev/laravel-box#1]
Hi I got this error when i try call return Box::connect() 

Call to a member function getBody() on null
at Box::dopost() in Box.php line 60

**Comment by dcblogdev** [comment]
thanks, I've added better error handling into the package, also added support for Guzzle 7 which is needed for Laravel 7/8 

Can you try it again?

**Comment by ksonia90** [comment]
Thanks! I'm able to get the access token noww :D
